# Generated by Django 4.2.1 on 2023-06-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.CharField(default=10, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='variant',
            field=models.CharField(default=10, max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.IntegerField(max_length=100),
        ),
    ]
